"""create user and blog table migrations

Revision ID: de05d5c89566
Revises: 8fa156542ae2
Create Date: 2023-08-02 13:50:04.260273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de05d5c89566'
down_revision = '8fa156542ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
